/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor;

import cliente.vistaCliente;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alice
 */
public class Vista extends javax.swing.JFrame {
    private ArrayList<String> clientes = new ArrayList<String>();

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setTitle("Cliente");
    }

    private Socket s;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtIp = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        lblDirIp = new javax.swing.JLabel();
        lblPuerto = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        fieldPassword = new javax.swing.JPasswordField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(102, 102, 255));
        btnLogin.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, 30));
        btnLogin.getAccessibleContext().setAccessibleName("btnLogin");

        btnSignup.setBackground(new java.awt.Color(102, 102, 255));
        btnSignup.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Registrarse");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        lblUser.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblUser.setText("Usuario:");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblPassword.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblPassword.setText("Contraseña:");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 2, 20)); // NOI18N
        jLabel6.setText("Cliente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 290, 0));

        txtIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpActionPerformed(evt);
            }
        });
        jPanel1.add(txtIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 100, -1));

        txtPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuertoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, -1));

        lblDirIp.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblDirIp.setText("Dirección ip:");
        jPanel1.add(lblDirIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblPuerto.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lblPuerto.setText("Puerto:");
        jPanel1.add(lblPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 10));

        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        String tipo = "registro";
        String ip = txtIp.getText();
        int puerto = Integer.parseInt(txtPuerto.getText());
        Socket s;
        String user = txtUser.getText();
        char[] passTemp = fieldPassword.getPassword();
        String password = new String(passTemp);
        System.out.println(password);
        try {
            s = new Socket(ip, puerto);
            PrintStream ps = new PrintStream(s.getOutputStream());
            ps.println(tipo + "@" + user + ":" +password);
            ps.flush();
            s.close();
        } catch (IOException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
        /**/
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        String ip = txtIp.getText();
        int puerto = Integer.parseInt(txtPuerto.getText());
        String user = txtUser.getText();
        char[] passTemp = fieldPassword.getPassword();
        String password = new String(passTemp);
        
        try{
            String ruta = "C:\\Users\\alice\\Desktop\\usuariosExistentes.txt";
            FileReader fr=new FileReader(ruta);
            BufferedReader br=new BufferedReader(fr);
            String datos=br.readLine();
            while(datos!=null){
                if(datos.equals(user+":"+password)){
                    try{
                        s = new Socket (ip,puerto);
                        InputStreamReader  entradaSocket = new InputStreamReader(s.getInputStream());
                       // BufferedReader entrada = new BufferedReader(entradaSocket);
                       // DataOutputStream salida = new DataOutputStream(s.getOutputStream());
                        PrintStream escribir = new PrintStream(s.getOutputStream());
                        escribir.println(user);
                        escribir.flush();
                        vistaCliente vc = new vistaCliente(s,user);
                        vc.setVisible(true);
                        Thread a = new Thread(vc);
                        a.start();
                        dispose();
                    }catch(Exception e) {
                        System.out.println("Ha habido un fallo en el cliente "+e.getMessage());
                    }
                    JOptionPane.showMessageDialog(this, "Haz ingresado correctamente");
                        System.out.println("Bienvenido : " + user + ". Te has conectado al servidor :" + ip +" El el puerto : "+puerto);
                        break;
                }else{
                    datos=br.readLine();
                }
            }
            
        }catch(Exception e){}
               
    }//GEN-LAST:event_btnLoginActionPerformed

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordActionPerformed

    private void txtPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuertoActionPerformed

    private void txtIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnSignup;
    public javax.swing.JPasswordField fieldPassword;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel lblDirIp;
    public javax.swing.JLabel lblPassword;
    public javax.swing.JLabel lblPuerto;
    public javax.swing.JLabel lblUser;
    public javax.swing.JTextField txtIp;
    public javax.swing.JTextField txtPuerto;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
